"""Add user_email_constraint

Revision ID: e88698b5354b
Revises: 104a25a7c3b8
Create Date: 2026-03-02 20:14:40.247336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e88698b5354b'
down_revision: Union[str, Sequence[str], None] = '104a25a7c3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('campaigns_creator_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['creator_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('contributions_campaign_id_fkey'), 'contributions', type_='foreignkey')
    op.drop_constraint(op.f('contributions_user_id_fkey'), 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contributions', 'campaigns', ['campaign_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_email_lower', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key(op.f('contributions_user_id_fkey'), 'contributions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('contributions_campaign_id_fkey'), 'contributions', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_creator_id_fkey'), 'campaigns', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
